version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.2
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
    - 17.0.2
  - dependency-name: semantic-release
    versions:
    - 17.3.9
    - 17.4.1
  - dependency-name: "@types/react"
    versions:
    - 17.0.2
  - dependency-name: react-scripts
    versions:
    - 4.0.2
  - dependency-name: react-app-rewired
    versions:
    - 2.1.8
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: npm
  directory: "/packages/service"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.34
    - 14.14.35
    - 14.14.37
  - dependency-name: ts-loader
    versions:
    - 8.0.17
    - 8.0.18
    - 8.1.0
  - dependency-name: ts-jest
    versions:
    - 26.5.1
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: "@nestjs/testing"
    versions:
    - 7.6.12
    - 7.6.13
    - 7.6.14
  - dependency-name: "@nestjs/core"
    versions:
    - 7.6.12
    - 7.6.13
    - 7.6.14
  - dependency-name: "@nestjs/platform-express"
    versions:
    - 7.6.12
    - 7.6.13
    - 7.6.14
  - dependency-name: "@nestjs/common"
    versions:
    - 7.6.12
    - 7.6.13
    - 7.6.14
  - dependency-name: xmldom
    versions:
    - 0.5.0
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: npm
  directory: "/packages/webapp"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-hook-form
    versions:
    - 6.15.3
    - 6.15.4
    - 6.15.5
    - 7.0.0
    - 7.0.5
  - dependency-name: ts-loader
    versions:
    - 8.0.17
    - 8.0.18
    - 8.1.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.34
    - 14.14.35
    - 14.14.37
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
    - 17.0.2
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@types/react"
    versions:
    - 17.0.2
  - dependency-name: react-scripts
    versions:
    - 4.0.2
  commit-message:
    prefix: chore
    include: scope
