trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '10.x'

- task: DownloadGitHubRelease@0
  displayName: 'Download Release'
  inputs:
    connection: 'tecidosbr'
    userRepository: 'tecidosbr/gestao-contratos-service'
    defaultVersionType: 'latest'
    itemPattern: '*.tgz'
    downloadPath: '$(System.DefaultWorkingDirectory)'

- task: ExtractFiles@1
  displayName: 'Extract Release Files'
  inputs:
    archiveFilePatterns: '$(System.DefaultWorkingDirectory)/**/*.tgz'
    cleanDestinationFolder: true
    overwriteExistingFiles: false
    destinationFolder: '$(System.DefaultWorkingDirectory)'

- task: Npm@1
  displayName: 'Install Dependencies'
  inputs:
    command: 'ci'
    workingDir: '$(System.DefaultWorkingDirectory)/package'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/package'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/package-$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
