trigger: none

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: DownloadGitHubRelease@0
  displayName: 'Download Release'
  inputs:
    connection: 'github.com_lmarqs'
    userRepository: 'tecidosbr/gestao-normas'
    defaultVersionType: 'latest'
    itemPattern: '*.zip'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: ExtractFiles@1
  displayName: 'Extract Files'
  inputs:
    archiveFilePatterns: '$(System.ArtifactsDirectory)/*.zip'
    cleanDestinationFolder: true
    overwriteExistingFiles: false
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Avaliação Gratuita(60b55c61-13b2-4600-869e-7aa1d496e967)'
    appType: 'webApp'
    WebAppName: 'gestao-normas-webapp'
    packageForLinux: '$(System.ArtifactsDirectory)/gestao-normas-webapp-*.zip'
    ScriptType: 'Inline Script'
    InlineScript: 'ls --hide=package | xargs rm -rf && mv package/build/* .'
    enableCustomDeployment: true
    DeploymentType: 'zipDeploy'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Avaliação Gratuita(60b55c61-13b2-4600-869e-7aa1d496e967)'
    appType: 'functionApp'
    WebAppName: 'gestao-normas-service'
    packageForLinux: '$(System.ArtifactsDirectory)/gestao-normas-service-*.zip'
    ScriptType: 'Inline Script'
    InlineScript: 'ls --hide=package | xargs rm -rf && mv package/* .'
    enableCustomDeployment: true
    DeploymentType: 'zipDeploy'