trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: CI
  displayName: 'Continuous Integration'
  jobs:
    - job: CI
      steps:

      - task: DownloadGitHubRelease@0
        displayName: 'Download Release'
        inputs:
          connection: 'tecidosbr'
          userRepository: 'tecidosbr/gestao-contratos'
          defaultVersionType: 'latest'
          itemPattern: '*.tgz'
          downloadPath: '$(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'

- stage: CD
  displayName: 'Continuous Deployment'
  jobs:
    - job: CD
      steps:
