trigger: none

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: DownloadGitHubRelease@0
  displayName: 'Download Release'
  inputs:
    connection: 'tecidosbr'
    userRepository: 'tecidosbr/gestao-contratos'
    defaultVersionType: 'latest'
    itemPattern: '*.zip'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy Webapp'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial(0fa5aa5e-6fee-485d-9fd6-db18a7b17c2b)'
    appType: 'webApp'
    WebAppName: 'gestao-contratos-webapp'
    packageForLinux: '$(System.ArtifactsDirectory)/gestao-contratos-webapp-*.zip'
    ScriptType: 'Inline Script'
    InlineScript: 'mv package/* .'
    enableCustomDeployment: true
    DeploymentType: 'webDeploy'
    RemoveAdditionalFilesFlag: true

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy Service'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial(0fa5aa5e-6fee-485d-9fd6-db18a7b17c2b)'
    appType: 'functionApp'
    WebAppName: 'gestao-contratos-service'
    packageForLinux: '$(System.ArtifactsDirectory)/gestao-contratos-service-*.zip'
    ScriptType: 'Inline Script'
    InlineScript: 'mv package/* .'
    enableCustomDeployment: true
    DeploymentType: 'webDeploy'
    RemoveAdditionalFilesFlag: true