trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: CI
  displayName: 'Continuous Integration'
  jobs:
    - job: CI
      steps:

      - task: DownloadGitHubRelease@0
        displayName: 'Download Release'
        inputs:
          connection: 'tecidosbr'
          userRepository: 'tecidosbr/gestao-contratos'
          defaultVersionType: 'latest'
          itemPattern: '*.tgz'
          downloadPath: '$(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'

- stage: CD
  displayName: 'Continuous Deployment'
  jobs:
    - job: CD
      steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'drop'
          downloadPath: '$(System.ArtifactsDirectory)'
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'Free Trial(0fa5aa5e-6fee-485d-9fd6-db18a7b17c2b)'
          appType: 'webAppLinux'
          WebAppName: 'gestao-contratos-webapp'
          packageForLinux: '$(System.ArtifactsDirectory)/**/gestao-contratos-webapp-*.tgz'
          RuntimeStack: 'NODE|14-lts'
