trigger: none

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: DownloadGitHubRelease@0
  displayName: 'Download Release'
  inputs:
    connection: 'tecidosbr'
    userRepository: 'tecidosbr/gestao-normas'
    defaultVersionType: 'latest'
    itemPattern: '*.zip'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial(0fa5aa5e-6fee-485d-9fd6-db18a7b17c2b)'
    appType: 'webApp'
    WebAppName: 'gestao-normas-webapp'
    packageForLinux: '$(System.ArtifactsDirectory)/gestao-normas-webapp-*.zip'
    enableCustomDeployment: true
    DeploymentType: 'webDeploy'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial(0fa5aa5e-6fee-485d-9fd6-db18a7b17c2b)'
    appType: 'functionApp'
    WebAppName: 'gestao-normas-service'
    packageForLinux: '$(System.ArtifactsDirectory)/gestao-normas-service-*.zip'