name: $(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
      - refs/heads/master
  batch: True

stages:
  - stage: Build
    jobs:
      - job: Build
        timeoutInMinutes: 0
        pool:
          vmImage: 'vs2017-win2016'
        steps:
          - checkout: self
          - task: NodeTool@0
            displayName: 'Use Node version'
            inputs:
              versionSpec: 14.15
          - task: Npm@1
            displayName: 'Install dependencies'
            inputs:
              command: ci
              verbose: false
          - task: Npm@1
            displayName: 'Run tests'
            inputs:
              command: custom
              customCommand: run test:azure
              verbose: false
          - task: Npm@1
            displayName: 'Prune dependencies'
            inputs:
              command: custom
              customCommand: prune --production
              verbose: false
          - task: ArchiveFiles@2
            displayName: Archive application
            inputs:
              rootFolderOrFile: $(System.DefaultWorkingDirectory)
              includeRootFolder: false
              archiveFile: $(Build.ArtifactStagingDirectory)/app-v$(Build.BuildId).zip
          - task: ArchiveFiles@2
            displayName: 'Archive tests'
            inputs:
              rootFolderOrFile: $(System.DefaultWorkingDirectory)/coverage
              includeRootFolder: false
              archiveFile: '$(Build.ArtifactStagingDirectory)/tests-v$(Build.BuildId).zip'
          - task: CopyFiles@2
            displayName: 'Archive ARM templates'
            inputs:
              SourceFolder: '.azure-pipelines'
              Contents: 'windows-webapp-template.json'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
              TargetPath: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'drop'

  - stage: Deploy
    jobs:
      - deployment: Deploy
        timeoutInMinutes: 0
        pool:
          vmImage: 'vs2017-win2016'
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@0
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: 'drop'
                    itemPattern: '**/app-v*.zip'
                    downloadPath: '$(System.ArtifactsDirectory)'
                - task: AzureResourceGroupDeployment@2
                  displayName: 'Create Azure App Service'
                  inputs:
                    azureSubscription: 'gestao-contratos-service - Azure'
                    resourceGroupName: 'gestao-contratos-service-rg'
                    location: 'South Central US'
                    csmFile: '$(System.DefaultWorkingDirectory)/**/windows-webapp-template.json'
                    overrideParameters: '-webAppName gestao-contratos-service -hostingPlanName gestao-contratos-service-plan -appInsightsLocation "South Central US" -sku "F1 Free"'
                - task: AzureRmWebAppDeployment@3
                  displayName: 'Deploy Azure App Service'
                  inputs:
                    azureSubscription: 'gestao-contratos-service - Azure'
                    WebAppName: 'gestao-contratos-service'
                    Package: '$(System.ArtifactsDirectory)/drop/app-v*.zip'
                    WebAppUri: webAppUrl
                    TakeAppOfflineFlag: true
                    UseWebDeploy: true
                    RenameFilesFlag: true
