name: 'Approve Security Updates'
on:
  pull_request:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
      uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: "${{ secrets.OWNER_GITHUB_TOKEN }}"