name: 'DevOps Pipeline'
on:
  pull_request:
  push:
   branches:
    - master
jobs:
  main:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:

    - name: 'Checkout Source Code'
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0

    - name: 'Fetch master'
      if: github.ref != 'refs/heads/master'
      run: git branch master origin/master

    - name: 'Install Dependencies'
      run: npm ci

    - name: 'Run Static checking'
      run: npm run lint

    - name: 'Build'
      run: npm run build

    - name: 'Test'
      run: npm run test

    - name: 'Publish Build Quality Report'
      uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: npm run test:cov
        coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov

    - name: 'Release'
      run: npm run release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Deploy'
      if: github.ref != 'refs/heads/master'
      uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: 'https://dev.azure.com/1228409/gestao-contratos-service'
        azure-pipeline-name: 'deploy'
        azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'

    - name: 'Approve Security Updates'
      if: github.ref != 'refs/heads/master' && (github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]')
      uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: "${{ secrets.OWNER_GITHUB_TOKEN }}"